/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class in_derros_jni_UDPStreamer */

#ifndef _Included_in_derros_jni_UDPStreamer
#define _Included_in_derros_jni_UDPStreamer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     in_derros_jni_UDPStreamer
 * Method:    _n_grabFrame
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_in_derros_jni_UDPStreamer__1n_1grabFrame
  (JNIEnv *, jobject);

/*
 * Class:     in_derros_jni_UDPStreamer
 * Method:    _n_sendFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_in_derros_jni_UDPStreamer__1n_1sendFrame
  (JNIEnv *, jobject);

/*
 * Class:     in_derros_jni_UDPStreamer
 * Method:    _n_showFrame_blocking
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_in_derros_jni_UDPStreamer__1n_1showFrame_1blocking
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
